apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   name: default-dev-role
   namespace: azuredevops-k8s
rules:
  - apiGroups: ["*","apps","extensions"]
    resources: ["deployments","pods","services","secrets","pods/logs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]