apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: default-dev-rolebinding
   namespace: azuredevops-k8s
subjects:
- kind: ServiceAccount
  name: azure-k8s-admin
  namespace: azuredevops-k8s
roleRef:
  kind: Role
  name: default-dev-role
  apiGroup: rbac.authorization.k8s.io

  
